[service]
port = 8080

[dingtalk]
webhook = "https://oapi.dingtalk.com/robot/send?access_token={access_token}"
secret = "{secret}"

[jira]
domain = "{domain}"

[user]
users = { 
    "{userKey1}"="{mobile1}",
    "{userKey2}"="{mobile2}",
    "{userKey3}"="{mobile3}"
}